apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongo-vault
  labels:
    app: flask-mongo-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-mongo-vault
  template:
    metadata:
      labels:
        app: flask-mongo-vault
      annotations:
        instrumentation.opentelemetry.io/inject-python: 'opentelemetry/instrumentation'
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-python-role"
        vault.hashicorp.com/agent-inject-secret-mongodb: "app/data/python"
        vault.hashicorp.com/agent-inject-template-mongodb: |
          {{- with secret "app/data/python" -}}
          {{ .Data.data | toJSON }}
          {{- end }}
    spec:
      containers:
      - name: flask-mongo-vault
        image: cauanliima/flask-mongo-vault:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production
        - name: PYTHONUNBUFFERED
          value: "1"
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10   # tempo para app iniciar
          periodSeconds: 15         # frequÃªncia da checagem
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: flask-mongo-vault-service
  labels:
    app: flask-mongo-vault
spec:
  type: NodePort
  selector:
    app: flask-mongo-vault
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31003

